flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/storage'
        public.storage:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: 'afi-cdn-images'
