parameters:
    env(APP_URL): ''
    env(WWW_URL): ''
    env(JWT_SECRET_KEY): ''
    env(JWT_PUBLIC_KEY): ''
    env(JWT_PASSPHRASE): ''
    app_url: '%env(APP_URL)%'
    www_url: '%env(WWW_URL)%'
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    php_errors:
        log: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
