monolog:
    channels:
        - deprecation

when@local:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                level: debug
                channels: ["!event"]
            console:
                type: stream
                path: php://stderr
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@rc:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: info
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            console:
                type: stream
                path: php://stderr
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!request"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
            nested:
                type: stream
                path: php://stderr
                level: info
                formatter: monolog.formatter.json

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: info
                handler: cloud_watch
                excluded_http_codes: [404, 405]
                buffer_size: 50
            console:
                type: stream
                path: php://stderr
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!request"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
            cloud_watch:
                type: service
                id: AsyncAws\Monolog\CloudWatch\CloudWatchLogsHandler
